name: Build EXE

on:
  workflow_dispatch: # 允许你在网页上点击按钮手动触发打包

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: PyInstaller Build
        run: |
          # 关键：使用 --collect-all 包含 faster_whisper 的所有依赖
          pyinstaller --noconfirm --onedir --windowed --collect-all faster_whisper main.py
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KotobaWhisper_Windows
          path: dist/main/
