name: Update fq.list
on:
  #workflow_dispatch:
  schedule:
   - cron: '0 */12 * * *'  # 每天每隔6小时执行一次

jobs:
  update-fq-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download file from URL
        run: |
          curl -o fq.list "https://vless.yuki.ren/8ed96004-092c-42e9-9922-06a5080cdacc?base64"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f fq.list  # 不再使用 -f 选项
          git commit -m "Update fq.list"
          git push
