name: Git push assets to "release" branch with variables
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # 每天每隔6小时执行一次
jobs:
  update-fq-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download file from URL
        run: |
          wget https://vless.yuki.ren/8ed96004-092c-42e9-9922-06a5080cdacc?base64 -O fq.list
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Set variables
        run: |
          RELEASE_NAME=$(date +"%Y%m%d%H%M")
          TAG_NAME=$(date +"%Y%m%d%H%M")
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB
      - name: Create release branch
        run: |
          git checkout -b release
      - name: Git push assets to "release" branch
        run: |
          git add fq.list
          git commit -m "Update fq.list"
          git push -f origin release
