name: Run Script Every 12 Hours

on:
  schedule:
    - cron: '0 */12 * * *'  # 每隔12小时执行一次

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Bash
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run the script
      run: |
        url="https://www.dabai.in/link/2DDql9XsQEAdWpB8?sub=3"
        fq_list="fq.list"
        
        decoded_content=$(curl -s "$url" | base64 -d)
        
        new_content1="vless://0b6b461b-11cb-4aac-d7f6-bd267cc04bca@cloudflare.yuki.ren:443?encryption=none&security=tls&sni=de.yuki.ren&alpn=h2%2Chttp%2F1.1&fp=safari&type=ws&host=de.yuki.ren&path=%2Fbilibili%3Fed%3D2048#DE-FSN-kvm"
        new_content2="vless://a281f067-af59-4184-e4f9-e9a0f6d7c9fb@cloudflare.yuki.ren:443?encryption=none&security=tls&sni=us.yuki.ren&fp=safari&type=ws&host=us.yuki.ren&path=%2Fbilibili%3Fed%3D2048#US-CHI-kvm"
        encoded_new_content1=$(echo -n "$new_content1" | base64)
        encoded_new_content2=$(echo -n "$new_content2" | base64)
        
        final_content="$decoded_content\n$encoded_new_content1\n$encoded_new_content2"
        
        echo -e "$final_content" > "$fq_list"
