name: Download and Upload Release Asset with Name and Version
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download file
        run: |
          wget https://vless.yuki.ren/8ed96004-092c-42e9-9922-06a5080cdacc?base64 -O fq.list
      - name: Set release name and version
        id: set_release_info
        run: |
          echo "RELEASE_NAME=${{ github.run_id }}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ github.run_id }}" >> $GITHUB_ENV
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./fq.list
          asset_nam
