name: Update fq.list
on:
  workflow_dispatch:
  schedule:
   - cron: '0 9 * * *'  
jobs:
  update-fq-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download file from URL
        run: |
          curl -o fq.list "https://vless.yuki.ren/8ed96004-092c-42e9-9922-06a5080cdacc?base64"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f fq.list
          git commit -m "Update fq.list"
          git push -f
