name: 更新文件

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜执行 (UTC 时间)
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: 下载文件
        run: curl -o halflife.txt https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad3.txt
      
      - name: 复制文件到项目目录
        run: cp halflife.txt https://github.com/soulmatelh/freeFQ/halflife.txt
